apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tetris
  name: tetris
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tetris
  template:
    metadata:
      labels:
        app: tetris
    spec:
      containers:
      - image: lrakai/tetris
        name: tetris
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tetris
  name: tetris
spec:
  type: NodePort
  ports:
  - name: "tetris-service"
    port: 5005
    targetPort: 80
    nodePort: 31006
  selector:
    app: tetris