apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
spec:
  selector:
    matchLabels:
      name: netflix
  template:
    metadata:
      labels:
        name: netflix
    spec:
      containers:
        - name: netflix
          image: yormengh/netflix
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: netflix-service
spec:
  type: NodePort
  selector:
    name: netflix
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80